### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by nomadkode** [bellshade/bellshade-website#11]
Fitur dark mode dong, boleh pake tailwind atau pake vanilla.

**Comment by hendraaagil** [comment]
IMO, kalau mau pakai tailwind ga perlu custom scss jangan di campur custom scss & tailwind
Paling scss cuma buat pake directive @apply aja biar lebih pendek kalau mau pake ke class html

**Comment by nomadkode** [comment]
> IMO, kalau mau pakai tailwind ga perlu custom scss jangan di campur custom scss & tailwind
> Paling scss cuma buat pake directive @apply aja biar lebih pendek kalau mau pake ke class html

ini maksudnya yg dark mode feature nya om?

**Comment by hendraaagil** [comment]
Ya semua om, jadi kita rewrite
Kalau mau tailwind ya tailwind aja, itu juga bakal ngaruh ke penggunaan dark mode nanti

**Comment by hendraaagil** [comment]
Atau mungkin aku bikin issue baru aja buat rewrite styling nya

**Comment by nomadkode** [comment]
> Atau mungkin aku bikin issue baru aja buat rewrite styling nya

boleh om gass biar lebih rapih

**Comment by nomadkode** [comment]
@bellshade/webpage-team siapa yg mau ngerjain fitur ini?

**Comment by hasheemi** [comment]
> Fitur dark mode dong, boleh pake tailwind atau pake vanilla.
Saya bang @nomadkode , insyallah bisa

**Comment by reacto11mecha** [comment]
Issue ini di close karena udah ada pr #69
